Set Theme "Catppuccin Mocha"
Set FontFamily "JetBrainsMono Nerd Font"
Set FontSize 18
Set Width 1920
Set Height 1080

Type "bun start"

Enter

Sleep 2

Type 'j'
Type 'j'

Enter
Sleep 2
Type 'j'

Enter
Sleep 2
Type 'j'

Enter
Sleep 2
Type@0.5 'h'
Type@0.5 'h'
Enter

Sleep 1
Escape
Sleep 2

Type '1'
Type 'a'
Sleep 3
Escape
Sleep 1
Ctrl+p
Sleep 1

Type@0.3 'theme'
Enter

Type@1.4 'k'
Type@1.4 'k'
Type@1.4 'j'
Type@1.4 'j'

Escape
Sleep 2

Ctrl+Q
